/////////////////////////////////////
// Color Palette
// Names were generated by at chir.ag/projects/name-that-color/
/////////////////////////////////////

export const PALETTE = {
  white: "#fff",
  white_20: "#CBC7C6",
  white_50: "#898989",
  white_75: "#d4d4d4",

  black: "#000",
  black_20: "#171717",
  black_50: "#5A5858",
  black_75: "#403E3E",

  gray: "#878787",
  silverChalice: "#ACACAC",
  codGray: "#111010",
  lavenderRose: "#FFA7FF",
  swirl: "#CECCC3",
  transparent: "#00000000",
};
