/////////////////////////////////////
// Color Palette
// Names were generated by at chir.ag/projects/name-that-color/
/////////////////////////////////////

export const PALETTE = {
  white: "#fff",
  white_20: "#CBC7C6",
  white_50: "#898989",
  white_75: "#d4d4d4",

  black: "#000",
  black_20: "#171717",
  black_50: "#7F7D7C",
  black_75: "#403E3E",

  gray: "#878787",
  silverChalice: "#ACACAC",
  codGray: "#111010",
  lavenderRose: "#FFA7FF",
  swirl: "#CECCC3",
  transparent: "#00000000",
};

export const theme = {
  light: {
    background: PALETTE.swirl,
    primary: PALETTE.black,
    primary_20: PALETTE.black_20,
    primary_50: PALETTE.black_50,
    primary_75: PALETTE.black_75,
    secondary: PALETTE.gray,

    gradient: {
      backgroundToTransparent: `linear-gradient(
        ${PALETTE.swirl},
        ${PALETTE.transparent}
      )`,
    },
  },
  dark: {
    background: PALETTE.codGray,
    primary: PALETTE.white,
    primary_20: PALETTE.white_20,
    primary_50: PALETTE.white_50,
    primary_75: PALETTE.white_75,
    secondary: PALETTE.gray,

    gradient: {
      backgroundToTransparent: `linear-gradient(
        ${PALETTE.codGray},
        ${PALETTE.transparent}
      )`,
    },
  },
};
